AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A simple AWS Lambda for posting a card to a set
Resources:
  postCardsFx:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/postCard-1.0-SNAPSHOT.jar
      Handler: com.revature.post_cards.PostCardsHandler
      Runtime: java8.al2
      Description: Java function
      MemorySize: 256
      Timeout: 30
      Tracing: Active
      Policies:
        - arn:aws:iam::011217676466:policy/dynamo-full-access
